#!/bin/zsh

GIT_TAG=1
ODOO_VERSION=13.0
MODULES=($(awk -F= '{print $1}' managed_modules.txt))

for MODULE in "${MODULES[@]}"
do
    MODULE_PATH="$MODULE"
    MODULE=$(basename "$MODULE")

    if [[ -d "$MODULE_PATH" ]]
    then
        # get version of module
        VERSION=$(grep 'version' "$MODULE_PATH/__manifest__.py" | sed "s;';\";g"  | sed "s/,//g" )
        VERSION=$(echo "{ $VERSION }" | jq .version | sed 's/"//g' | sed 's/null//g')

        # set default version
        [ -z "$VERSION" ] && VERSION=0.0

        # check if oca version or enterprise version
        if echo "$VERSION" | grep -q "^[0-9]\." 
        then
            VERSION=$ODOO_VERSION.$VERSION.$GIT_TAG
        fi

        # copy module to managed folder
        echo "Copy module $MODULE $VERSION to managed folder"
        mkdir -p managed-modules
        MANAGED_MODULE_PATH="managed-modules/$MODULE-$VERSION"
        cp -r $MODULE_PATH $MANAGED_MODULE_PATH

        # configure and zip module
        echo "Remove auto install option"
        sed -i '' -e "s/'auto_install': True,/'auto_install': False,/" $MANAGED_MODULE_PATH/__manifest__.py
        echo "zip module $MODULE"
        zip -q -r  $MANAGED_MODULE_PATH.zip $MANAGED_MODULE_PATH
    fi
done