#!/bin/zsh

ODOO_ADDONS_PATH="$(pwd)/addons"

for MODULE in "${(@f)"$(<managed_modules.txt)"}"
{
    MODULE_PATH="$MODULE"
    MODULE=$(basename "$MODULE")

    echo "Copy module $MODULE to addons folder"
    cp -r $MODULE_PATH $ODOO_ADDONS_PATH/$MODULE
}