#!/bin/zsh

ODOO_ADDONS_PATH="$(pwd)/addons"

for MODULE in "${(@f)"$(<managed_modules.txt)"}"
{
    MODULE=$(basename "$MODULE")

    echo "Remove module $MODULE from addons folder"
    rm -rf $ODOO_ADDONS_PATH/$MODULE
}