on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clone taskfile
        run: ./task clone-taskfile
      - name: Load SSH key
        run: ./task load-ssh-key
        env:
          GIT_AUTHOR_NAME: Mint Bot
          GIT_AUTHOR_EMAIL: bot@mint-system.ch
          GIT_SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_MINTBOT }}
          GIT_SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY_MINTBOT }}
      - name: Load version
        run: ./task load-latest-revision 18.0
      - name: Download git folder odoo
        run: ./task download-git-folder odoo
      - name: Login docker
        run: ./task container-login ${{ secrets.CONTAINER_REGISTRY_USERNAME }} ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
      - name: Build
        run: ./task build
