on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract version from tag
        id: extract_version
        run: |
          TAG=${GITHUB_REF##*/}
          VERSION=$(echo $TAG | cut -d'.' -f1,2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Using version: $VERSION"
      - name: Clone taskfile
        run: ./task clone-taskfile
      - name: Load SSH key
        run: ./task load-ssh-key
        env:
          GIT_AUTHOR_NAME: Mint Bot
          GIT_AUTHOR_EMAIL: bot@mint-system.ch
          GIT_SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_MINTBOT }}
          GIT_SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY_MINTBOT }}
      - name: Load version
        run: ./task load-version $VERSION
      - name: Load latest revision
        run: ./task load-latest-revision $VERSION
      - name: Download git folder odoo
        run: ./task download-git-folder odoo
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install
        run: ./task install
      - name: Login docker
        run: ./task login-docker ${{ secrets.CONTAINER_REGISTRY_USERNAME }} ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
      - name: Build
        run: ./task build images/odoo --push
