on:
  pull_request:
    branches:
      - "16.0*"
  push:
    branches:
      - "16.0"

jobs:
  task-all:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run task test-docker
        run: ./task test-docker