on:
  pull_request:
    branches:
      - "main*"
  push:
    branches:
      - "main"

jobs:
  task-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Run task install
        run: ./task install
        env:
          ODOO_REVISION: "18.0"
      - name: Run task install-odoo-scripts
        run: ./task install-odoo-scripts
      - name: Run task test-project
        run: ./task test-project
        env:
          ODOO_REVISION: "18.0"
