ARG ODOO_IMAGE

FROM $ODOO_IMAGE

USER root

RUN apt-get update && \
apt-get install -y --no-install-recommends \
gettext

USER odoo

ENV ADDONS_PATH=/usr/lib/python3/dist-packages/odoo/addons

RUN pip install prometheus-client

COPY ./image/odoo.conf.template /etc/odoo/

COPY ./image/entrypoint.sh /
